FROM node:18.10.0-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install


RUN npx ngcc --properties es2023 browser module main --first-only --create-ivy-entry-points
COPY . .
CMD ["npm","run","start"]