version: "3"
services:
 db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tylerjames05
      POSTGRES_USER: admin
      POSTGRES_DB: hhcsauthdb
    volumes:
      - ./postgres-data:/var/lib/postgresq   
      
 nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:8080"     
 api:
    image: postgresapi
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /src/node_modules
      - .:/src
 client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
        
   

    

    

 