version: "3"
services:
 db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tylerjames05
      POSTGRES_USER: admin
      POSTGRES_DB: hhcsauthdb
    volumes:
      - ./postgres-data:/var/lib/postgresq
    ports:
      - "5432:5432"
 nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"     
 api:
    image: postgresapi
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /src/node_modules
      - .:/src
    ports:
      - "13000:9000"
 pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80" 
 client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
        
   

    

    

 