services:
 db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tylerjames05
      POSTGRES_USER: admin
      POSTGRES_DB: hhcsauthdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresq   
    networks:
      - internalnet 
 #api:
 #   image: postgresapi
 #   build:
 #     dockerfile: Dockerfile.dev
 #     context: ./server
 #   volumes:
 #     - /src/node_modules
 #     - .:/src
 #   networks:
 #     - internalnet
 #   ports:
 #     - "9000:9000"
 #client:
 #   container_name: hhcsmanagerweb
 #   build:
 #     dockerfile: Dockerfile
 #     context: ./client
 #   stdin_open: true
 #   environment:
 #     - CHOKIDAR_USEPOLLING=true   
 #   ports:
 #     - "80:80"
 #   networks:
 #     - internalnet
 #   volumes:
 #     - /app/node_modules
 #     - ./client:/app      
 #nginx:
 #  build: ./nginx
 #  restart: always
 #  ports:
 #   - "80:80"
 #  links:
 #  - api
 #  - client
networks:
 internalnet:
  driver: bridge
 
        
   
        
   

    

    

 